name: caching 
on:
    workflow_dispatch:
        inputs:
         use-cache:
            type: boolean
            default: true
            description: wether to use caching or not
         node-version:
            description: node version.
            type: choice
            options:
              - 18.x
              - 20.x
              - 21.x
            default: 20.x        
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: cachingreact/react-app
        steps:
         - name: checkout code
           uses: actions/checkout@v4
         - name: setup Node
           uses: actions/setup-node@v3
           with:
            node-version: ${{ inputs.node-version}}
         - name: install dependencies
           run: npm ci
         - name: run tests
           run: npm run test
         - name: building
           run: npm run build
         - name: dploying to nonprod
           run: echo " deploying to non prod"