name: contexts
on: 
    push:
    workflow_dispatch:
env:
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR : " workflow"
jobs:
    echo-data:
        runs-on: ubuntu-latest
        env: 
             MY_WORKFLOW_VAR: "job"
             MY_OVERWRITTEN_VAR : " job"
        steps:
         - name: display information
           run: |
             echo "Event name: ${{ github.event_name }}"
             echo " Ref : ${{ github.ref }}"
             echo " Sha ${{ github.sha }}"
             echo "actor ${{ github.actor }}"
             echo "Workflow ${{ github.workflow }}"
             echo " Run id ${{ github.run_id }}"
             echo " run number ${{ github.run_number }}"
         - name: retrieve variables
           run: |
             echo "variable value: ${{ vars.MY_VAR }}"
         - name: print env variables
           env:
             MY_OVERWRITTEN_VAR: "step"
           run: |
             echo "workflow env : ${{ env.MY_WORKFLOW_VAR }}"
             echo "Overwriiten env : ${{ env.MY_WORKFLOW_VAR }}"
         - name: print env variables
           run: |
             echo "workflow env : ${{ env.MY_WORKFLOW_VAR }}"
             echo "Overwriiten env : ${{ env.MY_WORKFLOW_VAR }}"
