name: custom actions
on:
    workflow_dispatch:

env:
    working-directory: react/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory}}
        steps:
            - uses: actions/checkout@v3
            - name: set up node and dependencies
              uses: ./.github/actions/composite-cache-dependencies
              with:
                node-version: 20.x
                working-dir: ${{ env.working-directory}}
            - name: Test
              run: npm run test
        
            - name: build
              run: npm run build
            