name: custom actions
on:
    workflow_dispatch:
        inputs:
            target-env:
                description:  controls dependecies installed
                type: choice
                options:
                    - dev
                    - prod

env:
    working-directory: react/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory}}
        steps:
            - uses: actions/checkout@v3
            - name: set up node and dependencies
              uses: ./.github/actions/composite-cache-dependencies
              with:
                node-version: 20.x
                working-dir: ${{ env.working-directory}}
                target-env: ${{ inputs.target-env}}
            - name: Test
              run: npm run test
        
            - name: build
              run: npm run build
            