name: functions
on:
    pull_request:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps: 
         - name: failing step
           run: exit 1 
         - name: i will be skipped
           if: ${{ success() }}
           run: echo "i will print if previous step succeed"