name: reusable workflow
on: 
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/reusable.yaml
        with:
            target-directory: dummy-dir
    print-outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: print outputs
              run: |
                echo "build status is ${{ needs.deploy.outputs.build-status }}"
                echo "URL:  ${{ needs.deploy.outputs.url }}"