name: reusable workflow
on:
    workflow_dispatch:
        inputs:
            target-directory:
                type: string
                required: true
        outputs:
            build-status:
                description: status of build process
                value: ${{ jobs.deploy.outputs.build-status }}

            url:
                description: url of deployed application
                value: ${{ jobs.deploy.outputs.url}}

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.build-status}}
            url: ${{ steps.deploy.outputs.url}}
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Build
              id: build
              run: | 
               echo "building using  ${{ inputs.target-directory }}"
               echo "build-status=success" >> "$GITHUB_OUTPUT"
            - name: Deploy
              id: deploy
              run: |
               echo " deploying bild artifacts"
               echo " url=https://www.google.com" >> "$GITHUB_OUTPUT"