name: using actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
             working-directory: using-actions/react-app
        steps:
         - name: checkout the code
           uses: actions/checkout@v4

         - name: Show repo structure
           run: ls -R

         - name: Setup Node
           uses: actions/setup-node@v3
           with:
            node-version: '20'
            cache: npm

         - name: check node and npm version
           run: |
            node -v
            npm -v
        

         - name: install dependencies
           run: npm ci
           
        