name: workflow events
on: push
jobs:
    workflow:
        runs-on: ubuntu-latest
        steps:
         - name: show the runner
           run: echo "I triggered by a ${{ github.event_name}} event."